# Fase de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

# Copiar todos os arquivos para o container
COPY . .

# Restaurar dependências
RUN dotnet restore "BotTelegram.csproj"

# Publicar o projeto
RUN dotnet publish "BotTelegram.csproj" -c Release -o /app/publish

# Fase de runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "BotTelegram.dll"]
