# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["BotTelegram.csproj", "./"]
RUN dotnet restore "BotTelegram.csproj"

COPY . .
RUN dotnet publish "BotTelegram.csproj" -c Release -o /app/publish

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "BotTelegram.dll"]
