# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

# Copia tudo
COPY . .

# Vai para a pasta onde está o projeto
WORKDIR /app/BotTelegram

# Restaura pacotes
RUN dotnet restore BotTelegram.csproj

# Publica a aplicação
RUN dotnet publish BotTelegram.csproj -c Release -o /app/out

# Etapa de runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build /app/out .

ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "BotTelegram.dll"]
