# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

# Copia tudo para o container
COPY . .

# Vai para a pasta onde está o projeto
WORKDIR /app/BotTelegram

# Restaura os pacotes NuGet
RUN dotnet restore BotTelegram.csproj

# Publica o projeto
RUN dotnet publish BotTelegram.csproj -c Release -o /app/out

# Etapa de runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

# Copia o build da etapa anterior
COPY --from=build /app/out .

# Define porta e entrada
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "BotTelegram.dll"]
